# numpy practice session

In [1]:
#import this libraray in jupitor notebook

import numpy as np


# creating an array using numpy

In [2]:
food = np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
price[2]

5

In [9]:
price[0:]

array([5, 5, 5])

In [10]:
food[1]

'samosa'

In [12]:
price.mean()

5.0

In [13]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
#specific interval

np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
#table of 5

np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [30]:
#line space

np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [32]:
#specify your data type

np.ones(50 , dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int8)

In [34]:
#specify your data type

np.ones(50 , dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
#array functions

a=np.array([10,12,15,2,4,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. , 100. , 320. ,   0.5,  10.3])

In [7]:
a.sort()
a

array([  0.5,   2. ,   4. ,  10. ,  10.3,  12. ,  15. , 100. , 320. ])

In [8]:
b=np.array([10.2,3.4,53.6,45.5])
b

array([10.2,  3.4, 53.6, 45.5])

In [12]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,  10. ,  10.3,  12. ,  15. , 100. , 320. ,
        10.2,   3.4,  53.6,  45.5])

In [13]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,  10. ,  10.2,  10.3,  12. ,  15. ,
        45.5,  53.6, 100. , 320. ])

# 2d arrays


In [19]:
a= np.array ([[1,2] , [5,1]])
a

array([[1, 2],
       [5, 1]])

In [20]:
b=np.array ([[6,7] , [8,9]])
b

array([[6, 7],
       [8, 9]])

In [21]:
c= np.concatenate((a,b))
c

array([[1, 2],
       [5, 1],
       [6, 7],
       [8, 9]])

In [22]:
c= np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [5, 1],
       [6, 7],
       [8, 9]])

In [23]:
c= np.concatenate((a,b) , axis=1)
c

array([[1, 2, 6, 7],
       [5, 1, 8, 9]])

In [24]:
a.ndim

2

In [25]:
a.size

4

In [29]:
np.reshape(a, newshape=(2,2))

array([[1, 2],
       [5, 1]])

In [30]:
#convert 1d into 2d

a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#row wise 2d
b= a [np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
b.shape

(1, 9)

In [34]:
#coloumn wise 2d
b= a [: , np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [35]:
a*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [36]:
a.sum()

45

In [37]:
a.mean()

5.0