In [2]:
import numpy as np
a=np.array([5,5,5,])
a

array([5, 5, 5])

In [3]:
type(a)

numpy.ndarray

In [ ]:
# list of lists
 b= np.array([[]])

In [5]:
len(a)

3

In [6]:
a[0]

5

In [7]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [9]:
f=np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [11]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#linerly spcaed arrays
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
#specific data type in arrays

np.ones(5, dtype=np.int8)

array([1, 1, 1, 1, 1], dtype=int8)

In [34]:
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

In [23]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
np.empty((3,4 ))

array([[1.01855798e-312, 1.06099790e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.06099790e-312, 1.03977794e-312, 1.23075756e-312,
        1.20953760e-312],
       [1.12465777e-312, 9.76118064e-313, 1.01855798e-312,
        1.90979621e-312]])

In [35]:
#making and shaping a 3d array

np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])